name: crysta_pay
description: A modern cryptocurrency wallet application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # QR & Images
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.2.0
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Utils
  intl: ^0.20.2
  logger: ^2.0.2+1
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700