name: crysta_pay
description: A modern cryptocurrency wallet application
version: 1.0.0+1
publish_to: 'none' # Không xuất bản gói này lên pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.6

  # Blockchain & crypto
  web3dart: ^2.7.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  encrypt: ^5.0.3
  wallet: ^0.0.11
  solana: ^0.31.0+1
  walletconnect_dart: ^0.0.11

  bitcoin_base: ^4.0.0

  # UI & Utils
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  uuid: ^3.0.7
  equatable: ^2.0.5
  go_router: ^14.3.0
  get_it: ^7.7.0

  # Storage
  shared_preferences: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4

  # Network
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0

  # Tools
  intl: ^0.20.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
